[book]
authors = ["HiPoster Team"]
language = "zh-cn"
src = "src"
title = "GPUI 实战进阶：从零到一构建高性能桌面应用"

[output.html]
git-repository-url = "https://github.com/obity/hiposter-gpui"
edit-url-template = "https://github.com/obity/hiposter-gpui/edit/master/book/src/{path}"

[preprocessor.index]
# 允许搜索
[output.html.search]
limit-results = 30
copy-js = true

[output.pdf]
